### ISSUE TITLE
Clearly state if the beacon/dataset is for testing purposes

### ISSUE THREAD

**Issue by sdelatorrep** [ga4gh-beacon/specification-v2#10]
We can follow a similar approach to the one used in [GA4GH service-info spec](https://github.com/ga4gh-discovery/ga4gh-service-info/blob/develop/service-info.yaml):
```yaml
environment:
  type: string
  description: 'Environment the service is running in. Use this to distinguish between production, development and testing/staging deployments. Suggested values are prod, test, dev, staging. However this is advised and not enforced.'
```
